name: Docker Image CI

on:
  push:
    branches: [ "master", "database/cockroachdb", "database/spanner" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the AliyunCloud
      run: docker build . --file docker/src/AliyunCloud/Dockerfile --tag my-image-name:$(date +%s) && docker system prune --all --force

    - uses: actions/checkout@main
    - name: Build the capacitor
      run: docker build . --file docker/src/capacitor/Dockerfile --tag my-image-name:$(date +%s) && docker system prune --all --force

    - uses: actions/checkout@main
    - name: Build the electron
      run: docker build . --file docker/src/electron/Dockerfile --tag my-image-name:$(date +%s) && docker system prune --all --force

    - uses: actions/checkout@main
    - name: Build the rust
      run: docker build . --file docker/src/rust/Dockerfile --tag my-image-name:$(date +%s) && docker system prune --all --force
